- hosts: localhost
  connection: local
  become_user: yoshiyuki_hisamatsu
  gather_facts: yes

  vars_files:
    - vars/common.yml

  vars:
    homebrew_cask_apps:
      - cursor
      - figma
      - microsoft-teams
      - zoom

  roles:
    - role: geerlingguy.mac.homebrew
      tags: homebrew
