- hosts: localhost
  connection: local
  become_user: yoshiyuki_hisamatsu
  gather_facts: yes

  vars:
    ansible_user_id: yoshiyuki_hisamatsu
    ansible_user_gid: 20

    homebrew_cask_apps:
      - cursor

  roles:
    - role: geerlingguy.mac.homebrew
      tags: homebrew
