- hosts: localhost
  connection: local
  become_user: hisamatsuyoshiyuki
  gather_facts: yes

  vars:
    ansible_user_id: hisamatsuyoshiyuki
    ansible_user_gid: 20

    homebrew_taps: 
      - mackerelio/mackerel-agent
      - kayac/tap
      - Songmu/tap

    homebrew_cask_apps:
      - atok
      - discord
      - docker
      - google-chrome
      - iterm2
      - logi-options-plus
      - microsoft-office
      - miro
      - mysqlworkbench
      - neat
      - notion
      - session-manager-plugin
      - scroll-reverser
      - slack
      - tableplus
      - visual-studio-code
      - zoom

    homebrew_installed_packages:
      - actionlint
      - asdf
      - awscli
      - coreutils
      - ecschedule
      - ecspresso
      - gh
      - gsed
      - hadolint
      - jq
      - jsonnet
      - mkr
      - pinact
      - pre-commit
      - sheldon
      - speedtest-cli
      - terraform
      - tflint
      - triby
      - tmux
      - vim
      - zsh

    mas_installed_apps:
      - { name: "Bitwarden", id: 1352778147 }
      - { name: "Display Menu", id: 549083868 }
      - { name: "Keynote", id: 409183694 }

    dotfiles_repo: "git@github.com:karia/dot-files.git"
    dotfiles_repo_version: master
    dotfiles_repo_local_destination: "~/projects/karia/dot-files"
    dotfiles_files:
      - .asdfrc
      - .config
      - .gitconfig
      - .gitignore_global
      - .tmux.conf
      - .tool-versions
      - .vimrc
      - .zshrc

  roles:
    - role: geerlingguy.mac.homebrew
      tags: homebrew
    - role: geerlingguy.mac.mas
      tags: mas
    - role: geerlingguy.dotfiles
      tags: dotfiles
