- hosts: localhost
  connection: local
  become_user: yoshiyuki_hisamatsu
  gather_facts: yes

  vars:
    ansible_user_id: yoshiyuki_hisamatsu
    ansible_user_gid: 20

    homebrew_cask_apps:
      - neat
      - raycast

    homebrew_installed_packages:
      - fzf
      - gh
      - ghq
      - git
      - gnu-sed
      - jnv
      - jq
      - mise
      - sheldon
      - speedtest-cli
      - tmux
      - vim
      - zsh

    dotfiles_repo: "git@github.com:karia/dot-files.git"
    dotfiles_repo_version: master
    dotfiles_repo_local_destination: "~/ghq/github.com/karia/dot-files"
    dotfiles_files:
      - .claude
      - .config
      - .gitconfig
      - .gitconfig-work
      - .gitignore_global
      - .tmux.conf
      - .vimrc
      - .zshrc

  roles:
    - role: geerlingguy.mac.homebrew
      tags: homebrew
    - role: geerlingguy.dotfiles
      tags: dotfiles
